"""
Configuration shema and constants for audio sources
The configuration schema is refreshed for each call, so the attributes returned can be dependent on
the current active audio source.
For example an audio device with more than one channel allows selection of the channel to monitor
"""

import logging
import voluptuous as vol
import sounddevice as sd

from ledfx.effects.melbank import FFT_SIZE
from ledfx.api.websocket import WEB_AUDIO_CLIENTS


_LOGGER = logging.getLogger(__name__)

# schema attributes that the API may modify
PERMITTED_AUDIO_KEYS = (
    "min_volume",
    "audio_device",
    "audio_channel",
    "delay_ms",
    "pitch_method",
    "onset_method",
    "pitch_tolerance",
)

# Hostapi name used for Web Audio sources
WEB_AUDIO_NAME = 'WEB AUDIO'

# Starting number to use when spoofing PortAudio device indexes for Web Audio Clients
WEB_AUDIO_BASE_INDEX = 100


# https://aubio.org/doc/latest/pitch_8h.html
PITCH_METHODS = [
    "yinfft",
    "yin",
    "yinfast",
    # TODO retest mcomb and fcomb with the latest aubio release
    # mcomb and fcomb appears to just explode something deeep in the aubio code, no logs, no errors, it just dies.
    # "mcomb",
    # "fcomb",
    "schmitt",
    "specacf",
]
# https://aubio.org/doc/latest/specdesc_8h.html
ONSET_METHODS = [
    "energy",
    "hfc",
    "complex",
    "phase",
    "wphase",
    "specdiff",
    "kl",
    "mkl",
    "specflux",
]

TEMPO_METHODS = [
    "default",  # aubio only provides one tempo method so far
]


def available_audio_devices() -> dict:
    """
    Returns a dict with names of the available audio devices, for use by the schema.
    Use available_audio_device_details() if you need to work with the device attributes.
    Local devices are keyed by PortAudio index so their indexes should not change if audio devices are added or removed
    Web Audio devices are keyed using a spoofed PortAudio index, and may change.
    """
    # return {k: format_device_name(device) for k, device in available_audio_device_details().items()}
    return {device['index']: format_device_name(device) for device in available_audio_device_details().values()}


def format_device_name(device: dict) -> str:
    """
    Formats the name of the audio device for use within the UI and the schema.
    Uses 'hostapi name: device name' to retain compatibility with the front end UI, which groups devices by hostapi
    """
    return f"{device['hostapi_name']}: {device['name']}"


def refresh_audio_schema(running_config=None) -> vol.Schema:
    """
    Returns the audio config schema for the current available audio devices
    """
    default_device_index = default_audio_device_details()['index']

    return vol.Schema(
        {
            vol.Optional(
                "audio_device",
                default=default_device_index
            ): vol.Any(vol.In(available_audio_devices()), vol.SetTo(default_device_index)),
            vol.Optional(
                "audio_channel",
                default=0
            ): vol.Any(vol.In(available_audio_channels(running_config)), vol.SetTo(0)),
            vol.Optional("sample_rate", default=60): int,
            vol.Optional("mic_rate", default=44100): int,
            vol.Optional("fft_size", default=FFT_SIZE): int,
            vol.Optional("min_volume", default=0.2): vol.All(
                vol.Coerce(float), vol.Range(min=0.0, max=1.0)
            ),
            vol.Optional(
                "delay_ms",
                default=0,
                description="Add a delay to LedFx's output to sync with your audio."
                            + "Useful for Bluetooth devices which typically have a short audio lag.",
            ): vol.All(vol.Coerce(int), vol.Range(min=0, max=5000)),
            vol.Optional(
                "pitch_method",
                default="yinfft",
                description="Method to detect pitch",
            ): vol.In(PITCH_METHODS),
            vol.Optional(
                "tempo_method",
                default="default"
            ): vol.In(TEMPO_METHODS),
            vol.Optional(
                "onset_method",
                default="hfc",
                description="Method used to detect onsets",
            ): vol.In(ONSET_METHODS),
            vol.Optional(
                "pitch_tolerance",
                default=0.8,
                description="Pitch detection tolerance",
            ): vol.All(vol.Coerce(float), vol.Range(min=0.0, max=2)),
        },
        extra=vol.ALLOW_EXTRA,
    )


def available_audio_device_details() -> dict:
    """
    Returns a dict of audio device attributes, keyed by device index.
    Ignores devices with no input channels.
    Ignores ASIO devices (legacy compatibility).
    The device index is generated by _format_device_index().
    """
    _LOGGER.debug('Refreshing available audio devices')
    available_devices = {}

    for device in sd.query_devices():
        if device["max_input_channels"] == 0 or "asio" in device["name"].lower():
            continue
        device["hostapi_name"] = sd.query_hostapis(device["hostapi"])["name"]
        # index = format_device_name(device)
        index = device["index"]   # Use the PortAudio index
        available_devices[index] = device

    # Note: WEB_AUDIO_CLIENTS is a set. Sorting helps make things deterministic,
    # but the calculated client indexes will still change if a client is added or removed.
    for idx, client in enumerate(sorted(WEB_AUDIO_CLIENTS)):
        device = {
            "hostapi_name": WEB_AUDIO_NAME,
            "name": f"{client}",
            "max_input_channels": 1,
            "client": client,
        }
        index = WEB_AUDIO_BASE_INDEX + idx
        available_devices[index] = device

    return available_devices


def available_audio_channels(running_config) -> list:
    """Returns a list of the available audio channels for the current active sound device"""
    _LOGGER.debug('Refreshing available audio channels')
    if running_config is None:
        return [0]  # use the default channel

    active_device_idx = running_config.get("audio_device")
    if active_device_idx is None:
        return [0]

    active_device = available_audio_device_details().get(active_device_idx)
    if active_device is not None:
        return list(range(active_device["max_input_channels"]))

    _LOGGER.warning('Unable to determine how many audio channels are available on the active audio device.')
    return [0]   # should never get here...


def default_audio_device_details() -> dict:
    """
    Returns a dict with attributes for the default device to use for audio input
    In order of preference:
     - if using Windows WASAPI, the first available loopback device
     - the default local sound device, if available
     - the first available Web Audio client
    """
    # The default input device index is not always valid (i.e no default input devices)
    available_devices = available_audio_device_details()

    if len(available_devices) == 0:
        _LOGGER.warning(
            "No valid audio input devices found. Unable to use audio reactive effects."
        )
        return {}

    for index, device in available_devices.items():
        if "WASAPI" in device["hostapi_name"] and "loopback" in device["name"].lower():
            _LOGGER.debug(
                "Setting audio loopback device %s as default input device",
                device["name"],
            )
            return device

    default_input_device_idx = sd.default.device["input"]
    for device in available_devices.values():
        if device['index'] == default_input_device_idx:
            _LOGGER.debug(
                "Setting local default %s as default input device",
                device['name']
            )
            return device

    # Return the first valid input device if we can't find a valid local input device
    first_valid_idx = next(iter(available_devices))
    _LOGGER.debug(
        "Setting %s as default input device",
        available_devices[first_valid_idx]['name']
    )
    return available_devices[first_valid_idx]
