"""
Configuration shema and constants for audio sources
The configuration schema is refreshed for each call, so the attributes returned can be dependent on
the current active audio source.
For example an audio device with more than one channel allows selection of the channel to monitor
"""

import logging
import voluptuous as vol
import sounddevice as sd

from ledfx.effects.melbank import FFT_SIZE
from ledfx.api.websocket import WEB_AUDIO_CLIENTS


_LOGGER = logging.getLogger(__name__)

# schema attributes that the API may modify
PERMITTED_AUDIO_KEYS = (
    "min_volume",
    "audio_device",
    "audio_channel",
    "delay_ms",
    "pitch_method",
    "onset_method",
    "pitch_tolerance",
)

# Hostapi name used for Web Audio sources
WEB_AUDIO_NAME = 'WEB AUDIO'

# https://aubio.org/doc/latest/pitch_8h.html
PITCH_METHODS = [
    "yinfft",
    "yin",
    "yinfast",
    # TODO retest mcomb and fcomb with the latest aubio release
    # mcomb and fcomb appears to just explode something deeep in the aubio code, no logs, no errors, it just dies.
    # "mcomb",
    # "fcomb",
    "schmitt",
    "specacf",
]
# https://aubio.org/doc/latest/specdesc_8h.html
ONSET_METHODS = [
    "energy",
    "hfc",
    "complex",
    "phase",
    "wphase",
    "specdiff",
    "kl",
    "mkl",
    "specflux",
]

TEMPO_METHODS = [
    "default",  # aubio only provides one tempo method so far
]


def _format_device_index(device: dict) -> str:
    """
    Formats the index that will be used to identify the audio device within the UI and the schema.
    Now uses 'hostapi name: device name' so that indexes do not change if audio devices are added or removed
    The colon seperator is to retain compatibility with the front end UI, which groups devices by hostapi
    """
    return f"{device['hostapi_name']}: {device['name']}"


def refresh_audio_schema(running_config=None) -> vol.Schema:
    """
    Returns the audio config schema for the current available audio devices
    """
    available_devices = available_audio_devices().keys()
    default_device = _format_device_index(default_audio_device())

    return vol.Schema(
        {
            vol.Optional(
                "audio_device",
                default=default_device,
            ): vol.In(available_devices),
            vol.Optional(
                "audio_channel",
                default=0
            ): vol.All(vol.Coerce(int), vol.In(available_audio_channels(running_config))),
            vol.Optional("sample_rate", default=60): int,
            vol.Optional("mic_rate", default=44100): int,
            vol.Optional("fft_size", default=FFT_SIZE): int,
            vol.Optional("min_volume", default=0.2): vol.All(
                vol.Coerce(float), vol.Range(min=0.0, max=1.0)
            ),
            vol.Optional(
                "delay_ms",
                default=0,
                description="Add a delay to LedFx's output to sync with your audio."
                            + "Useful for Bluetooth devices which typically have a short audio lag.",
            ): vol.All(vol.Coerce(int), vol.Range(min=0, max=5000)),
            vol.Optional(
                "pitch_method",
                default="yinfft",
                description="Method to detect pitch",
            ): vol.In(PITCH_METHODS),
            vol.Optional(
                "tempo_method",
                default="default"
            ): vol.In(TEMPO_METHODS),
            vol.Optional(
                "onset_method",
                default="hfc",
                description="Method used to detect onsets",
            ): vol.In(ONSET_METHODS),
            vol.Optional(
                "pitch_tolerance",
                default=0.8,
                description="Pitch detection tolerance",
            ): vol.All(vol.Coerce(float), vol.Range(min=0.0, max=2)),
        },
        extra=vol.ALLOW_EXTRA,
    )


def available_audio_devices() -> dict:
    """
    Returns a dict of audio device attributes, keyed by device index.
    Ignores devices with no input channels.
    Ignores ASIO devices (legacy compatibility).
    The device index is generated by _format_device_index().
    """
    _LOGGER.debug('Refreshing available audio devices')
    available_devices = {}

    for device in sd.query_devices():
        if device["max_input_channels"] == 0 or "asio" in device["name"].lower():
            continue
        device["hostapi_name"] = sd.query_hostapis(device["hostapi"])["name"]
        index = _format_device_index(device)
        available_devices[index] = device

    for client in WEB_AUDIO_CLIENTS:
        device = {
            "hostapi_name": WEB_AUDIO_NAME,
            "name": f"{client}",
            "max_input_channels": 1,
            "client": client,
        }
        index = _format_device_index(client)
        available_devices[index] = device

    return available_devices


def available_audio_channels(running_config) -> list:
    """Returns a list of the available audio channels for the current active sound device"""
    _LOGGER.debug('Refreshing available audio channels')
    if running_config is None:
        return [0]  # use the default channel

    active_device_idx = running_config.get("audio_device")
    if active_device_idx is None:
        return [0]

    active_device = available_audio_devices().get('active_device_idx')
    if active_device is not None:
        return list(range(active_device["max_input_channels"]))

    _LOGGER.warning('Unable to determine how many audio channels are available on the active audio device.')
    return [0]   # should never get here...


def default_audio_device() -> dict:
    """
    Returns a dict with attributes for the default device to use for audio input
    In order of preference:
     - if using Windows WASAPI, the first available loopback device
     - the default local sound device, if available
     - the first available Web Audio client
    """
    # The default input device index is not always valid (i.e no default input devices)
    available_devices = available_audio_devices()

    if len(available_devices) == 0:
        _LOGGER.warning(
            "No valid audio input devices found. Unable to use audio reactive effects."
        )
        return {}

    for index, device in available_devices.items():
        if "WASAPI" in device["hostapi_name"] and "loopback" in device["name"].lower():
            _LOGGER.debug(
                "Setting audio loopback device %s as default input device",
                device["name"],
            )
            return device

    default_input_device_idx = sd.default.device["input"]
    if default_input_device_idx in available_devices:
        _LOGGER.debug(
            "Setting local default %s as default input device",
            available_devices[default_input_device_idx]['name']
        )
        return available_devices[default_input_device_idx]

    # Return the first valid input device if we can't find a valid local input device
    first_valid_idx = next(iter(available_devices))
    _LOGGER.debug(
        "Setting %s as default input device",
        available_devices[first_valid_idx]['name']
    )
    return available_devices[first_valid_idx]
